#!/usr/bin/env bash
export MCTESTER_GAMEDIR=/tmp/mctester/game
#export MCTESTER_UPLOAD_URL=http://92f9a67e.ngrok.io/upload


mkdir -p /tmp/mctester/game/screenshots/fail
wget https://imgur.com/download/K1F6TZV -O /tmp/mctester/game/screenshots/fail/satImage.png

npm install -g mctester-uploader
mctesterupload
